package business.city;

import business.city.as.ASCity;
import business.city.factory.ASCityFactory;
import business.client.TClient;
import business.client.as.ASClient;
import business.client.factory.ASClientFactory;
import business.rental.TRental;
import business.rental.as.ASRental;
import business.rental.factory.ASRentalFactory;
import business.vehicle.TVehicle;
import business.vehicle.as.ASVehicle;
import business.vehicle.factory.ASVehicleFactory;
import integration.city.dao.DAOCity;
import integration.city.factory.DAOCityFactory;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.Collection;
import java.util.Date;


public class ASCityTest {

    private static ASCity as;

	@BeforeEach
	private void setUp() throws Exception {
		DAOCity dao = DAOCityFactory.getInstance().generateDAOCity();
		dao.deleteAll();
		as = ASCityFactory.getInstance().generateASCity();
	}

	//create method tests
	@Test
	public void createCitySuccessful(){
		TCity tc = new TCity(null, "Madrid", false);
		assert(as.create(tc) > 0);
	}

	@Test (expected = IncorrectInputException.class)
	public void createCityIncorrectInput1(){
		TCity tc = new TCity(-1, "Madrid", false); //id it's generated by database,
        // so in create method must be null as input
		as.create(tc);
	}

	@Test (expected = IncorrectInputException.class)
	public void createCityIncorrectInput2(){
		TCity tc = new TCity(null, "Madrid", true); //active must be false as input
		as.create(tc);
	}

	//EN FUNCION DE SI HAY CAMBIOS O NO EN LOS CASOS DE USO QUITARLO
	@Test (expected = ASException.class)
	public void createCityAlreadyExists(){
		TCity old = new TCity(null, "Madrid",false);
		as.create(old);

		TCity tc = new TCity(null, "Madrid", false); //city already exists
		as.create(tc);
	}

	//drop method tests

	@Test
	public void dropCitySuccessful(){
		TCity tmp = new TCity(null,"Madrid",false);

		Integer id = as.create(tmp);

		assertEquals(as.drop(id),id);
	}


	@Test (expected = IncorrectInputException.class)
	public void dropCityIncorrectInput1(){
		Integer id = 0; //id must be > 0

		as.drop(id);
	}

	@Test (expected = IncorrectInputException.class)
	public void dropCityIncorrectInput2(){
	    Integer id = -1; //id must be > 0

		as.drop(id);
	}

	@Test (expected = ASException.class)
	public void dropCityNotExists(){
		Integer id = 1;

		as.drop(id);
	}

	@Test (expected = ASException.class)
	public void dropCityAlreadyInactive(){
		TCity tmp = new TCity(null,"Madrid",false);

		Integer id = as.create(tmp);
		as.drop(id);

		as.drop(id);
	}

	@Test (expected = ASException.class)
	public void dropCityWithActiveVehicles(){
		TCity tmp = new TCity(null,"Madrid",false);
		Integer id = as.create(tmp);

		ASVehicle asV = ASVehicleFactory.getInstance().generateASVehicle();
		TVehicle tv = new TVehicle(null,"Audi",false,
                false,0,1000);
		asV.create(tv);

		as.drop(id);
	}


	//show method tests
	@Test
	public void showCitySuccessful(){
		TCity tmp = new TCity(null,"Madrid",false);
		Integer id = as.create(tmp);

		TCity tc = as.show(id);

		assertEquals(tc.getId(),id);
		assertEquals(tc.getName(),"Madrid");
		assertTrue(tc.isActive());
	}

	@Test (expected = IncorrectInputException.class)
	public void showCityIncorrectInput1(){
		Integer id = 0; //id must be > 0

		as.show(id);
	}

	@Test (expected = IncorrectInputException.class)
	public void showCityIncorrectInput2(){
		Integer id = -1; //id must be > 0

		as.show(id);
	}

	@Test (expected = ASException.class)
	public void showCityNotExists(){
		Integer id = 1;

		as.show(id);
	}

	//showAll method tests
	@Test
	public void showAllCitySuccessful1(){
		TCity tc1 = new TCity(null,"Madrid",false);
		Integer idMad = as.create(tc1);
		tc1.setId(idMad);
		TCity tc2 = new TCity(null,"Barcelona",false);
		Integer idBcn = as.create(tc2);
		tc2.setId(idBcn);

		Collection<TCity> c = as.showAll();

		for(TCity tmp : c){
		    if(tmp.getId().equals(idMad))
			   assertTrue(checkTransferValues(tmp,"Madrid"));
			else
			    assertTrue(checkTransferValues(tmp,"Barcelona"));

		}
	}

    private boolean checkTransferValues(TCity tmp, String city) {
	    return tmp.getName().equals(city) && tmp.isActive();
    }

    @Test
	public void showAllCitySuccessful2(){
		Collection<TCity> c = as.showAll();
		assertTrue(c.isEmpty());
	}

	//TODO showClientsByCity tests
	@Test
	public void showClientsByCitySuccessful(){
        Date dFrom = new Date(1540373530000L);
        Date dTo = new Date(1543051930000L);
        //TODO refactorizar -> parte exitosa
        ASClient asC = ASClientFactory.getInstance().generateASClient();
		TClient tc = new TClient(null,"00000000X",0,false);
		Integer idC = asC.create(tc);

		TCity tcity = new TCity(null,"Madrid",false);
        Integer idCity = as.create(tcity);

        ASVehicle asV = ASVehicleFactory.getInstance().generateASVehicle();
        TVehicle tv = new TVehicle(null,"Audi",6000,0,
                false,idCity,false);
		Integer idV = asV.create(tv);

		ASRental asR = ASRentalFactory.getInstance().generateASRental();
        TRental tr = new TRental(null,idV,false,10,idC,dFrom,dTo);
        asR.create(tr);

        //TODO refactorizar -> parte fallo
        TClient tcFail = new TClient(null,"11111111X",0,false);
        Integer idCFail = asC.create(tcFail);

        TCity tcity2 = new TCity(null,"Barcelona",false);
        Integer idCity2 = as.create(tcity2);

        TVehicle tvFail = new TVehicle(null,"Audi",6000,0,
                false,idCity2,false);
        Integer idVFail = asV.create(tvFail);

        TRental trFail = new TRental(null,idVFail,false,10,idCFail,dFrom,dTo);
        asR.create(trFail);


        Collection<TClient> out = as.showClientsByCity(idCity);

        for(TClient client : out){
            assertEquals(client.getId(), idC);
            assertNotEquals(client.getId(),idCFail);
        }
	}







	//update method tests

	@Test
	public void updateCitySuccessful(){
		TCity tmp = new TCity(null,"Madrid",false);
		Integer id = as.create(tmp);

		TCity tc = new TCity(id,"Barcelona",true);
		id = as.update(tc);
		assertEquals(id,tc.getId());

		tmp = as.show(id);
		assertEquals(tmp.getName(),"Barcelona");
	}

	@Test (expected = ASException.class)
	public void updateCityIncorrectInput1(){
		TCity tmp = new TCity(0,"Madrid",false); //id must be > 0

		as.update(tmp);
	}

	@Test (expected = ASException.class)
	public void updateCityIncorrectInput2(){
		TCity tmp = new TCity(-1,"Madrid",false); //id must be > 0

		as.update(tmp);
	}

	@Test (expected = ASException.class)
	public void updateCityNotExists(){
		TCity tc = new TCity(32,"Barcelona",true);
		as.update(tc);
	}

}
